### ISSUE TITLE
6/17 TODO

### ISSUE THREAD

**Issue by heeeete** [heeeete/keynut#54]
## 📝 상세한 작업 항목(선택)

- [x] 상품 크게 보기 모바일 환경 조정
- [x] 상품 북마크 클릭시 서버에 저장
  - [x] 북마크된 상품이면 알려주기
- [x] 판매 상품에 오픈채팅 URL 이 있을 경우랑 없을 경우 체크해서 렌더링
